#!/bin/env python
# coding: utf-8

import sys
try:
   import M6
except ImportError:
   print >> sys.stderr, """\
There was a problem importing one of the Python modules
required to run M6. The error leading to this problem was:

   %s

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
%s

""" % (sys.exc_value, sys.version)
   sys.exit(1)

try :
    from M6.Slave.PL import PL_SSD
    PL_SSD.main('SSD')
except KeyboardInterrupt, e:
    print >> sys.stderr, "\n\nExiting on user cancel."
    sys.exit(1)
